Add anime dictionnary for rank
sschmidTU/anki-frequency-inserter pull request #9
Opened 2024-12-07 12:37 UTC by JSchoreels

I created this version for Anime ranking list based on this frequency list : 
https://www.reddit.com/r/LearnJapanese/comments/ilobcq/word_frequency_list_based_on_anime_and_some/

2025-01-09 15:05 UTC, sschmidTU commented on index_BCCWJ.html
> +  <meta property="og:title" content="Anki Frequency Inserter | Anime version"/>
wrong file (this is _BCCWJ.html). you already added this in _anime.html, so this change should just be reverted I think.

2025-01-09 15:06 UTC, sschmidTU commented on index_BCCWJ.html
> +  <title>Anki Frequency Inserter (Anime version)</title>
wrong file (this is _BCCWJ.html). you already added this in _anime.html, so this change should just be reverted I think.

2025-01-09 15:07 UTC, sschmidTU commented on index_anime.html
> +	  <h1><img src="assets/img/favicon.ico" height="32"/>  Anki Frequency Inserter (BCCWJ version)</h1>
change (BCCWJ version) to (anime version)

2025-01-09 15:08 UTC, sschmidTU commented on index_anime.html
> +Inserts Japanese word frequencies into a preexisting field (<i>FrequencyBCCWJ</i>) in your <a href="https://apps.ankiweb.net/" class="a-blue">Anki</a> notes/cards.<br>
potentially updated hover text

2025-01-09 15:09 UTC, sschmidTU commented on index_anime.html
> +using BCCWJ corpus
update text (BCCWJ -> anime), bonus: add link, change hover text

2025-01-09 15:10 UTC, sschmidTU commented
This is awesome, thanks! Just a few changes needed and this can be merged.
I can also do the changes if you want, then I'll just merge to a feature branch and make the changes.

2025-01-09 15:11 UTC, sschmidTU requested changes
just a few visual changes needed (in anime version, BCCWJ is referenced, and in BCCWJ, anime)

2025-01-09 15:21 UTC, sschmidTU commented
I posted about this and the BCCWJ long/short version issue on Wanikani forums btw:
https://community.wanikani.com/t/anki-word-frequency-inserter-learn-most-common-words-first/53407/44

2025-01-09 18:23 UTC, JSchoreels commented
Hello, no problem I'll check those comments tomorrow.

By the way, I also put the python script to transform from the .tsv to the json so if one day we want to generate another frequency list, it's a bit more easy. Maybe if you still have yours for the BCCWJ->json, could be useful too :)

2025-01-09 20:24 UTC, sschmidTU commented
Nice! I unfortunately don't have a script for BCCWJ, I just found a json somewhere. But BCCWJ is tsv too, so your python script can probably be adapted easily.

2025-01-14 10:22 UTC, JSchoreels commented
Hello, sorry I postponed a bit the change :) 

I pushed a new commit, does it look OK ? There is still 2-3 reference to BCCWJ but I was not sure if it would make sense to change those too

2025-01-16 19:00 UTC, sschmidTU approved these changes
Fine now with the changes, thanks! Merging.
There are still a few text spots where BCCWJ is referenced in anime and so on, I'll quickly fix them after merging.

2025-01-16 19:02 UTC, merged

2025-01-16 19:16 UTC, sschmidTU commented
Added some explanations and small fixes, see commit above =)